### ISSUE TITLE
[Issue]: Unable to build on Ubuntu 24.04 system using mainline 6.12.3-061203-generic kernel

### ISSUE THREAD

**Issue by melroy89** [ROCm/ROCm#4316]
### Problem Description

amdgpu-dkms build fails due to (please see `make.log` below!!): 

```
In file included from ./include/linux/rhashtable-types.h:12,
                 from ./include/linux/sched/ext.h:15,
                 from ./include/linux/sched.h:85,
                 from ./include/linux/dma-fence.h:21,
                 from /tmp/amd.jcuhIcCy/include/linux/dma-resv.h:43,
                 from /tmp/amd.jcuhIcCy/amd/amdkcl/dma-buf/dma-resv.c:37:
./include/linux/alloc_tag.h:212:2: error: expected identifier or ‘(’ before ‘{’ token
  212 | ({                                                                      \
      |  ^
./include/linux/slab.h:1053:49: note: in expansion of macro ‘alloc_hooks’
 1053 | #define kvrealloc(...)                          alloc_hooks(kvrealloc_noprof(__VA_ARGS__))
      |                                                 ^~~~~~~~~~~
/tmp/amd.jcuhIcCy/include/kcl/kcl_slab.h:42:14: note: in expansion of macro ‘kvrealloc’
   42 | extern void *kvrealloc(const void *p, size_t oldsize, size_t newsize, gfp_t flags);
      |              ^~~~~~~~~
  CC [M]  /tmp/amd.jcuhIcCy/amd/amdkcl/kcl_page_alloc.o
```

### Operating System

Linux Mint 22.1 (Ubuntu 24.04) kernel v

### CPU

AMD Ryzen Threadripper 7960X 24-Cores

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.3.0

### Steps to Reproduce

- Use Ubuntu 24.04
- Use the [latest mainline kernel](https://kernel.ubuntu.com/mainline/) (including headers and modules): v6.12.3-061203-generic
- Following: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html#rocm-install-quick

### Additional Information

[make.log](https://github.com/user-attachments/files/18596210/make.log)

**Comment by ppanchad-amd** [comment]
Hi @melroy89. Internal ticket has been created to investigate this issue. Thanks!

**Comment by darren-amd** [comment]
Hi @melroy89,

We currently do not support kernel version 6.12.3 on Ubuntu 24.04. Please refer to our [Supported Distributions](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-distributions), indicating support for kernel version 6.8 [GA] and 6.11 [HWE] for Ubuntu 24.04. Thanks!

**Comment by melroy89** [comment]
owh I see.

**Comment by melroy89** [comment]
However, at some point in time this kernel release will become the new LTS kernel. So at the end, you still might want to investigate the problem.

**Comment by melroy89** [comment]
Also also. You can't select ROCm v6.3.2 in the issue template. Just saying. I needed to update the issue description later.

**Comment by e-minguez** [comment]
Just in case this same error is happening if you are trying to make this work on Debian 12 with backported kernel (6.12)
